### PR TITLE
Uploads to S3

### PR DESCRIPTION
**Pull request by acdha**
Once we have hashes for a file, we need to upload them. This opens up a number of likely-subtickets, brain-dumped below:

* [x] Uploads only start after a file has been hashed so we can do end-to-end fixity checks
* [x] Retries for failed uploads – automatic with exponential backoff?
* [x] UI for selecting a starting directory
* [x] UI to enter S3 credentials
* [x] UI to display upload status and performance

### CODE REVIEW

**Comment by acdha** [comment]
A valid bag produced entirely in Chrome, uploaded directly to S3 and passing validation with py-bagit:

screenshot 2015-10-30 12 48 22 2

**Comment by acdha** [comment]
@eikeon @edsu Do you think the MD5 bits should block this branch merging? It's complicated by the lack of a fast JavaScript MD5 implementation since everyone is deprecating it and since it's transferring over HTTPS and we have a manifest I'm inclined to defer that to a separate ticket.

**Comment by edsu** [comment]
I definitely don't think MD5 support should block this being integrated. It will still create valid bags, and that's what this tool is for right?! 

Awesome work, btw.

**Comment by acdha** [comment]
@edsu That's what I was thinking – just wanted to run it by someone else to confirm I wasn't being too quick to dismiss it. Thanks!

**Comment by acdha** [comment]
The AWS S3 servers do not set CORS headers on the global responses, which makes it impossible for us to offer a nice <select> list of buckets. 

After https://github.com/LibraryOfCongress/bagger-js/commit/99e6cf76758726986b879376177eda3f63c776dd we at least allow you to test credentials before starting. I'm inclined to say this is ready to merge now.

**Comment by acdha** [comment]
@edsu @eikeon: this was inevitable – since Bag-Size isn't machine-readable, I had a missing newline which slipped past `bagit.py --validate`:

```Bag-Size: 2 MBPayload-Oxum: 2103158.3```

bdba499dcccc8339aafcf5723c6b7d0182d60289 fixes that

**Pull request merged**
